notice:
  type: [ "sc3", "local" ]
  report_error: true

school_notice:
  enabled: true
  url: "https://see.tongji.edu.cn/index"
  pages: [ "tz.htm", "gg.htm", "jz.htm", "jqzyhd.htm" ]

lecture:
  enabled: true
  url: "https://1.tongji.edu.cn/api/lectureservice/lectureHallApply/workbenchLectureList"